### ISSUE TITLE
Add 'Unobfuscate' JS

### ISSUE THREAD

**Issue by mattez** [atk14/Atk14Js#4]
In ATK14 is helper [block.no_spam](https://github.com/atk14/Atk14/blob/master/src/atk14/helpers/block.no_spam.php). Its full functionality is dependent on a jQuery plugin [Unobfuscate](https://github.com/bganicky/unobfuscate) by @bganicky.

If helper "block.no_spam" is an integral part of ATK14, then jQuery plugin [Unobfuscate](https://github.com/bganicky/unobfuscate) should also be somehow a part of ATK14.

**Comment by mattez** [comment]
Temporary solution:
add plugin via bower: `bower install --save "git://github.com/bganicky/unobfuscate#master"`
add `$(".atk14_no_spam").unobfuscate();` to JS

**Comment by yarri** [comment]
Source code of Unobfuscate was copied into another repository (https://github.com/atk14/UnobfuscateJs) and npm package has been created (https://www.npmjs.com/package/unobfuscatejs)

Included README contains more information.
